"""Generate WORLD-LOG.md — a readable digest of the world, for the repository.

The Chronicle is append-only and is now 24 MB across 105,576 entries, of which about
ninety-nine per cent is weather: 48,481 storms, 25,075 floods, 14,829 year headers.
Committing it would put a fresh 24 MB blob in git history on every update and bury the
interesting hundred lines inside the boring hundred thousand.

So this keeps the signal and drops the noise:

  * epochs, game-master notes, restores and corruption events -- in full, they are rare
  * speciation and extinction -- species-rank in full, subspecies counted per era
  * disasters -- counted per era rather than listed
  * the most recent entries -- so the tail of the story is always current

Run it whenever the log should be refreshed:

    .venv\\Scripts\\python.exe tools\\worldlog.py

It reads state/summary.json and chronicle/chronicle.md and writes WORLD-LOG.md. It never
writes to the world; it is safe to run against a live simulation.
"""
from __future__ import annotations

import io
import json
import os
import re
import sys
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHRONICLE = os.path.join(ROOT, "chronicle", "chronicle.md")
SUMMARY = os.path.join(ROOT, "state", "summary.json")
OUT = os.path.join(ROOT, "WORLD-LOG.md")

ERA = 1000          # years per bucket in the era tables
TAIL = 30           # how many recent entries to quote verbatim

# marker -> (label, keep-in-full?)
KIND = {
    "*": ("epoch", True),
    '"': ("game-master note", True),
    "&": ("gene invented", True),
    "$": ("intervention", True),
    "/": ("tuning", True),
    ">": ("seeding", True),
    ".": ("checkpoint", False),      # filtered below: only restores and corruption
    "+": ("speciation", False),
    "x": ("extinction", False),
    "V": ("volcano", False),
    "@": ("meteor", False),
    "^": ("wildfire", False),
    "=": ("flood", False),
    "!": ("storm", False),
    "#": ("cold snap", False),
    "~": ("year", False),
}

ENTRY = re.compile(r"^`(.)`\s+\*\*(.+?)\*\*\s+\(t(\d+)\)\s+—\s+(.*)$")
YEAR = re.compile(r"Year\s+([\d,]+)")


def parse(line):
    m = ENTRY.match(line.rstrip("\n"))
    if not m:
        return None
    mark, stamp, tick, text = m.groups()
    ym = YEAR.search(stamp)
    year = int(ym.group(1).replace(",", "")) if ym else 0
    return mark, stamp, int(tick), text, year


def main() -> int:
    if not os.path.exists(CHRONICLE):
        print("no chronicle at", CHRONICLE)
        return 1

    kept, recent = [], []
    per_era = defaultdict(Counter)
    totals = Counter()
    species_events = []

    with io.open(CHRONICLE, encoding="utf-8", errors="replace") as f:
        for line in f:
            e = parse(line)
            if not e:
                continue
            mark, stamp, tick, text, year = e
            label, full = KIND.get(mark, (mark, False))
            totals[label] += 1
            per_era[year // ERA * ERA][label] += 1

            if full:
                kept.append((tick, year, label, stamp, text))
            elif mark == "." and re.search(r"TIMELINE BRANCH|CORRUPT|resumed", text):
                kept.append((tick, year, "restore", stamp, text))
            elif mark in "+x" and " species " in (" " + text):
                # species-rank only; subspecies are counted, not listed
                species_events.append((tick, year, label, stamp, text))

            recent.append((mark, stamp, text))
            if len(recent) > TAIL:
                recent.pop(0)

    kept.sort()
    species_events.sort()

    state = {}
    if os.path.exists(SUMMARY):
        try:
            state = json.load(io.open(SUMMARY, encoding="utf-8"))
        except Exception:
            state = {}

    o = []
    w = o.append
    w("# PRIMORDIA — world log\n")
    w("*Generated by `tools/worldlog.py`. The full Chronicle is append-only, 24 MB and "
      "mostly weather; this is the signal from it, plus the world's current state.*\n")

    # ---------------------------------------------------------------- state
    if state:
        p = state.get("populations", {})
        m = state.get("matter", {})
        n = state.get("predator_niche", {})
        w("## Where it stands\n")
        w("| | |")
        w("|---|---|")
        w(f"| year | **{state.get('year', 0):,}** ({state.get('season','')}) |")
        w(f"| animals | {p.get('total_fauna', 0):,} "
          f"— {p.get('herbivore',0):,} herbivore / {p.get('omnivore',0):,} omnivore / "
          f"{p.get('carnivore',0):,} carnivore |")
        w(f"| plant biomass | {p.get('flora_biomass', 0):,.0f} |")
        w(f"| living species | {len(state.get('species', []))} "
          f"(of {state.get('species_total_ever', 0):,} ever named) |")
        w(f"| total matter | {m.get('total', 0):,.0f} "
          f"— the world is closed, so this should not move |")
        if n:
            w(f"| predator niche | {'open' if n.get('open') else 'shut'} "
              f"— needs attack power {n.get('power_needed', 0)}, "
              f"ceiling {n.get('genome_ceiling', 0)} |")
        w(f"| genetic variance | {state.get('genetic_variance', 0)} |")
        warn = state.get("warnings") or []
        w(f"| warnings | {'; '.join(warn) if warn else 'none'} |")
        w("")
        sp = state.get("species") or []
        if sp:
            w("### Living species\n")
            w("| species | population | mean diet | trend |")
            w("|---|---:|---:|---|")
            for s in sp:
                w(f"| {s.get('name','?')} | {s.get('pop',0):,} | "
                  f"{s.get('diet_mean',0):.3f} | {s.get('trend','—')} |")
            w("")
        genes = state.get("runtime_genes") or []
        if genes:
            w("### Genes that evolution did not invent\n")
            w("| gene | mean | carried by |")
            w("|---|---:|---:|")
            for g in genes:
                frac = g.get("frac_above_half")
                w(f"| {g.get('name','?')} | {g.get('mean',0):.3f} | "
                  f"{('%.0f%%' % (100*frac)) if frac is not None else '—'} |")
            w("")

    # ---------------------------------------------------------------- turning points
    w("## Turning points\n")
    w("*Epochs, invented genes, interventions, restores and the game-master's own "
      "reasoning — every one of these is rare enough to keep in full.*\n")
    for tick, year, label, stamp, text in kept:
        short = text if len(text) <= 600 else text[:600].rsplit(" ", 1)[0] + " …"
        w(f"- **{stamp}** · *{label}* — {short}")
    w("")

    # ---------------------------------------------------------------- taxonomy
    if species_events:
        w("## Species-rank origins and extinctions\n")
        w("*Subspecies are counted in the era table below rather than listed here.*\n")
        for tick, year, label, stamp, text in species_events:
            w(f"- **{stamp}** — {text}")
        w("")

    # ---------------------------------------------------------------- eras
    w("## By era\n")
    cols = ["speciation", "extinction", "volcano", "meteor", "wildfire", "flood",
            "storm", "cold snap"]
    w("| era | " + " | ".join(cols) + " |")
    w("|---" * (len(cols) + 1) + "|")
    for era in sorted(per_era):
        c = per_era[era]
        if not any(c.get(k) for k in cols):
            continue
        w(f"| {era:,}–{era + ERA - 1:,} | " +
          " | ".join(str(c.get(k, 0)) for k in cols) + " |")
    w("")
    w("**Totals:** " + " · ".join(
        f"{k} {v:,}" for k, v in totals.most_common() if k != "year") + "\n")

    # ---------------------------------------------------------------- tail
    w(f"## The last {len(recent)} entries\n")
    w("```")
    for mark, stamp, text in recent:
        w(f"{mark}  {stamp} — {text[:150]}")
    w("```")

    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(o) + "\n")
    size = os.path.getsize(OUT)
    print("wrote %s (%.0f KB) from %s entries"
          % (os.path.relpath(OUT, ROOT), size / 1024, sum(totals.values())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
